### ISSUE TITLE
sos doesn't compile with megaparsec-5.0.0?!

### ISSUE THREAD

**Issue by sjakobi** [schell/steeloverseer#10]
```
~ $ stack install steeloverseer
Run from outside a project, using implicit global project config
Using resolver: nightly-2016-06-21 from implicit global project's config file: /home/simon/.stack/global-project/stack.yaml
megaparsec-5.0.0: configure
megaparsec-5.0.0: build
megaparsec-5.0.0: copy/register
steeloverseer-2.0: download
steeloverseer-2.0: configure
steeloverseer-2.0: build
Completed 2 action(s).

--  While building package steeloverseer-2.0 using:
      /home/simon/.stack/setup-exe-cache/x86_64-linux/setup-Simple-Cabal-1.24.0.0-ghc-8.0.1 --builddir=.stack-work/dist/x86_64-linux/Cabal-1.24.0.0 build --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
    Logs have been written to: /home/simon/.stack/global-project/.stack-work/logs/steeloverseer-2.0.log

    Configuring steeloverseer-2.0...
    Building steeloverseer-2.0...
    Preprocessing library steeloverseer-2.0...
    [1 of 5] Compiling Sos              ( src/Sos.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.0.0/build/Sos.o )
    
    /tmp/stack27432/steeloverseer-2.0/src/Sos.hs:20:11: error:
        • Expecting two more arguments to ‘ParseError’
          Expected a type, but ‘ParseError’ has kind ‘* -> * -> *’
        • In the type ‘ParseError’
          In the definition of data constructor ‘SosCommandParseException’
          In the data declaration for ‘SosException’
```

If this is due to a missing or too large upper bound on megaparsec, it would be great if you could add a revision for that bound on Hackage!

**Comment by schell** [comment]
Oh no! Thanks for the catch. I'll check this out after work today.

**Comment by schell** [comment]
@sjakobi - I just pushed a new version to hackage. Please let me know if that fixes your issue (it did for me ;)).

**Comment by sjakobi** [comment]
Thanks for the quick response!

`stack`'s package index doesn't seem to pick up new versions from hackage so quickly though:

```
~ $ stack install steeloverseer-2.0.0.1
Run from outside a project, using implicit global project config
Using resolver: nightly-2016-06-21 from implicit global project's config file: /home/simon/.stack/global-project/stack.yaml
Didn't see steeloverseer-2.0.0.1 in your package indices.
Updating and trying again.
Fetching package index ...remote: Counting objects: 388, done.
remote: Compressing objects: 100% (287/287), done.
remote: Total 388 (delta 102), reused 344 (delta 89), pack-reused 0
Objekte werden empfangen: 100% (388/388), 134.40 KiB | 0 bytes/s, done.
Unterschiede werden aufgelöst: 100% (102/102), abgeschlossen mit 75 lokalen Objekten.
Von https://github.com/commercialhaskell/all-cabal-hashes
 - [Tag Aktualisierung] current-hackage -> current-hackage
Fetched package index.    
Populated index cache.    
The following package identifiers were not found in your indices: steeloverseer-2.0.0.1
Possible candidates: steeloverseer-2.0.
```

I can see the fixed bounds on hackage, so closing. Thanks again!
